import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '../app/components/Navbar'
import Head from '../app/components/Head'

import userData from '../../userTestData'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar role={userData.role} />
        <main className="ml-[275px] px-4 pt-6">
          <Head />
          <div className='py-4'>
            {children}
          </div>
        </main>
      </body>
    </html>
  )
}
